esphome:
  name: treppe-demo
  friendly_name: Treppe (Demo)

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "key"

ota:
  - platform: esphome
    password: "password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.1
    gateway: 192.168.0.254
    subnet: 255.255.255.0
    dns1: 192.168.0.254

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Treppe-Demo Fallback Hotspot"
    password: "password"

captive_portal:

web_server:
  port: 80

packages:
  basic: !include common/stairs/basic.yaml

substitutions:
  led_effect_up:             "Stufenlicht rauf colorized"
  led_effect_down:           "Stufenlicht runter colorized"
  led_effect_up_off:         "Stufenlicht rauf aus"
  led_effect_down_off:       "Stufenlicht runter aus"

  switchoff_delay_seconds:   10s

  cooldown_seconds:          3s

  leds_pro_stufe:            "{10, 10, 10, 20, 20, 20, 20, 10, 10, 10, 19, 20, 20, 10, 10}"

  farbe_je_stufe:            "{Color(0,102,102), Color(0,0,128), Color(0,102,102), Color(0,0,128), Color(0,102,102), Color(0,0,128), Color(0,102,102), Color(0,0,128), Color(0,102,102), Color(0,0,128), Color(0,102,102), Color(0,0,128), Color(0,102,102), Color(0,0,128), Color(0,102,102)}"

  led_anzahl:                "229"

